spring:
  application:
    name: sensitive-data-scanner

scanner:
  target-drives:
    - C:\
    - D:\

  supported-extensions:
    - pdf
    - docx
    - xlsx
    - txt
    - csv

  excluded-paths:
    - C:\Windows
    - C:\Program Files
    - C:\Program Files (x86)
    - C:\$Recycle.Bin
    - C:\ProgramData\Microsoft\Windows\WER
    - C:\ProgramData\Microsoft\Windows Defender
    - C:\ProgramData\Microsoft\Crypto
    - C:\ProgramData\Microsoft\Windows
    - C:\ProgramData\Microsoft\Network\Downloader
    - C:\ProgramData\Microsoft\Search\Data
    - C:\ProgramData\Microsoft\SmsRouter
    - C:\ProgramData\Microsoft\Diagnosis
    - C:\ProgramData\Microsoft\Provisioning
    - C:\ProgramData\Package Cache
    - C:\ProgramData\Packages
    - C:\ProgramData\ASUS
    - C:\ProgramData\Intel
    - C:\ProgramData\McAfee
    - C:\ProgramData\Application Data
    - C:\ProgramData\Documents
    - C:\ProgramData\Start Menu
    - C:\ProgramData\Templates
    - C:\Documents and Settings
    - C:\PerfLogs
    - C:\Recovery
    - C:\System Volume Information
    - C:\Users\Asus\Desktop\sensitive-data-scanner\reports

  excluded-folder-names:
    - node_modules
    - .git
    - .vscode
    - .idea
    - target
    - build
    - dist
    - .gradle
    - .m2
    - venv
    - .venv
    - site-packages
    - __pycache__
    - .cache
    - Google Cloud SDK
    - AppData

  schedule-cron: "0 0 */6 * * *"

  report:
    output-directory: reports
    format: csv
